---
- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: ohpc.yml
  when: ansible_connection == 'chroot'
