---
# tasks file for ansible-role-lustre_client

- name: Script for creating and bringing up IB partition ipoib devices
  template:
    src: ifcfg-ibpart-create.sh.j2
    dest: /usr/local/sbin/ifcfg-ibpart-create.sh
    mode: 0744
    owner: root
    group: root
  when: lustre_network_ib_partitions|bool

- name: Run the script from rc.local
  lineinfile:
    path: /etc/rc.d/rc.local
    line: '/usr/local/sbin/ifcfg-ibpart-create.sh'
  when: lustre_network_ib_partitions|bool

- name: Add extra IPs for Lnet multi-rail
  copy:
    src: ifcfg-create-alias.sh
    dest: /usr/local/sbin/ifcfg-create-alias.sh
    mode: 0744
    owner: root
    group: root
  when: lustre_network_ib_aliases|bool

- name: Run multi-rail setup from rc.local
  lineinfile:
    path: /etc/rc.d/rc.local
    line: '/usr/local/sbin/ifcfg-create-alias.sh'
  when: lustre_network_ib_aliases|bool

- name: Make sure rc.local is executable
  file:
    path: /etc/rc.d/rc.local
    mode: 0744
