---
# tasks file for ansible-role-lustre_client

- name: Script for creating and bringing up IB partition ipoib devices
  template:
    src: ifcfg-ibpart-create.sh.j2
    dest: /usr/local/sbin/ifcfg-ibpart-create.sh
    mode: 0744
    owner: root
    group: root
  when: lustre_network_ib_partitions|bool

- name: Run the script from rc.local
  lineinfile:
    path: /etc/rc.d/rc.local
    line: 'timeout 60 /usr/local/sbin/ifcfg-ibpart-create.sh'
  when: lustre_network_ib_partitions|bool

- name: Make sure rc.local is executable
  file:
    path: /etc/rc.d/rc.local
    mode: 0744
  when: lustre_network_ib_partitions|bool

- name: Add network device alias script for Lnet multi-rail
  copy:
    src: ifcfg-create-alias.sh
    dest: /usr/local/sbin/ifcfg-create-alias.sh
    mode: 0744
    owner: root
    group: root
  when: lustre_network_ib_aliases is defined

- name: Install systemd unit file for Lustre mount script
  template:
    src: lustre-mount.service.j2
    dest: /etc/systemd/system/lustre-mount.service
    mode: 0664
    owner: root
    group: root
  when: lustre_network_ib_aliases is defined

- name: Enable Lustre-mount unit
  systemd:
    name: lustre-mount
    enable: true
  when: lustre_network_ib_aliases is defined
