---
# tasks file for ansible-role-lustre_client

# here rpms's can be defined as a local file
- name: install lustre rpms (can be defined as a local file)
  yum: name="{{ item }}" state=present
  with_items: "{{ lustre_packages }}"

- name: Lustre modprobe.d confings
  template: src=lustre.conf.j2 dest=/etc/modprobe.d/lustre.conf
            owner=root group=root mode=0644

- name: Check Lustre networks
  command: /usr/sbin/ip link show {{ item }}
  with_items: "{{ lustre_network_devices|default([]) }}"
  register: lustre_networks
  failed_when: False
  changed_when: lustre_networks.rc != 0

- name: Bring up Lustre networks if down
  command: /usr/sbin/ifup {{ item[1] }}
  when: item[0].rc != 0
  with_nested:
    - "{{ lustre_networks.results }}"
    - "{{ lustre_network_devices|default([]) }}"

- name: Load Lustre modules
  modprobe: name=lustre

- name: create lustre mount directory
  file: "path={{ lustre_mount_dir }} state=directory mode={{ lustre_dir_mode }} owner=root group=root"

- name: Add Lustre entry to /etc/fstab, make sure it is mounted
  mount: fstype=lustre name="{{ lustre_mount_dir }}" opts="{{ lustre_mount_opts }}" src="{{ lustre_mount_src }}" state=mounted
